apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns-cert-manager.yaml
  - cert-manager.crds.yaml
  - cert-manager.yaml
  - cloudflare-api-token-secret-encrypted.yaml
  - clusterIssuer.yaml
  - certificate-carlescc.yaml
